name: sylt11
description: Using a shader, simply.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  flame: ^1.33.0
  flame_forge2d: ^0.19.2+1
  # flame_audio: ^2.1.0
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3
dev_dependencies:
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  shaders:
    - shaders/bg.frag
  # assets:
    # - assets/audio/megalergik.mp3
  
