name: Gh-Pages

on:
  push:
    branches:
      - main
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      itch_game: RabbidWorms
    steps:
      - uses: actions/checkout@main
      - uses: subosito/flutter-action@main
        with:
          channel: 'main'
      - run: flutter pub get
      - run: flutter create --platforms web .
      - run: flutter build web --release --base-href=/${{ env.itch_game }}/ --web-renderer=canvaskit
      
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: 'build/web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
   
      - name: Remove base tag from index.html
        run: sed -i '/<base href=".*">/d' ./build/web/index.html


    #   - uses: manleydev/butler-publish-itchio-action@master
    #     env:
    #       BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
    #       ITCH_GAME: ${{ env.itch_game }}
    #       ITCH_USER: nergnezor
    #       PACKAGE: build/web
    #       CHANNEL: html5
